name: Publish to PyPI

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

jobs:
  publish-pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Check that tag matches package version
        run: |
          python -m pip install .
          python check_tag.py
      - name: Build and publish package
        run: |
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
          python -m build
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{secrets.PYPI_API_TOKEN}}
