---

name: Test suite

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, pypy-3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install -r test_requirements.txt
          python -m pip install flake8
          python -m pip install isort
      - name: Run flake8
        run: flake8
      - name: Run isort
        run: isort .
      - name: Test with pytest
        run: make _covtest
